name: "Install Rust Tools"
description: "This action loads from cache, or installs rust tools and toolchains."

runs:
  using: composite
  steps:
    - name: Rust Tools Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.rustup/toolchains/
        key: ${{ runner.os }}-rust-tools-${{ hashFiles('**/toolchain.toml' )}}

    - name: Install Rust Tools
      shell: bash
      run: |
        # Extract tools section from toolchain.toml
        sed -n '/\[tools\]/,/^$/p' toolchain.toml | grep -v '\[tools\]' | while read -r line; do
          TOOL_NAME=$(echo "$line" | awk -F'=' '{gsub(/ /, "", $1); print $1}')
          TOOL_VERSION=$(echo "$line" | awk -F'=' '{gsub(/["'\'']/,"",$2); print $2}')
          cargo install "$TOOL_NAME" --version "$TOOL_VERSION" || true
        done       
